# Generated by Django 5.2.1 on 2025-05-16 11:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carpet',
            name='description',
        ),
        migrations.RemoveField(
            model_name='carpet',
            name='image',
        ),
        migrations.RemoveField(
            model_name='carpet',
            name='material',
        ),
        migrations.RemoveField(
            model_name='carpet',
            name='price',
        ),
        migrations.RemoveField(
            model_name='carpet',
            name='size',
        ),
        migrations.RemoveField(
            model_name='collection',
            name='description',
        ),
        migrations.RemoveField(
            model_name='collection',
            name='image',
        ),
        migrations.AddField(
            model_name='carpet',
            name='code',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Код названия'),
        ),
        migrations.AlterField(
            model_name='carpet',
            name='collection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carpets', to='catalog.collection', verbose_name='Коллекция'),
        ),
        migrations.AlterField(
            model_name='carpet',
            name='color',
            field=models.CharField(max_length=50, verbose_name='Цвет'),
        ),
        migrations.AlterField(
            model_name='carpet',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название ковра'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название коллекции'),
        ),
    ]
