# Generated by Django 5.2.1 on 2025-05-16 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_remove_carpet_description_remove_carpet_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carpet',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='carpets/', verbose_name='Изображение'),
        ),
    ]
