# Generated by Django 5.2.3 on 2025-06-13 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_carpet_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='carpet',
            name='main_colors',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
