# Generated by Django 5.2.3 on 2025-06-13 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_carpet_main_colors'),
    ]

    operations = [
        migrations.AddField(
            model_name='carpet',
            name='backing',
            field=models.CharField(blank=True, max_length=50, verbose_name='Основа'),
        ),
        migrations.AddField(
            model_name='carpet',
            name='density',
            field=models.CharField(blank=True, max_length=60, verbose_name='Плотность ворса'),
        ),
        migrations.AddField(
            model_name='carpet',
            name='manufacturing_method',
            field=models.CharField(blank=True, max_length=50, verbose_name='Способ производства'),
        ),
        migrations.AddField(
            model_name='carpet',
            name='material',
            field=models.CharField(blank=True, max_length=120, verbose_name='Состав'),
        ),
        migrations.AddField(
            model_name='carpet',
            name='pile_height',
            field=models.CharField(blank=True, max_length=30, verbose_name='Высота ворса'),
        ),
        migrations.AddField(
            model_name='carpet',
            name='weight',
            field=models.CharField(blank=True, max_length=30, verbose_name='Вес'),
        ),
    ]
