# Generated by Django 5.2.1 on 2025-07-18 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_carpet_backing_carpet_density_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carpet',
            name='style',
            field=models.CharField(choices=[('modern', 'Modern'), ('classic', 'Classic'), ('abstraction', 'Abstraction')], default='modern', max_length=20, verbose_name='Стиль'),
        ),
    ]
