# Generated by Django 5.2.1 on 2025-07-29 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_carpet_style'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carpet',
            name='backing',
        ),
        migrations.RemoveField(
            model_name='carpet',
            name='density',
        ),
        migrations.RemoveField(
            model_name='carpet',
            name='manufacturing_method',
        ),
        migrations.RemoveField(
            model_name='carpet',
            name='material',
        ),
        migrations.RemoveField(
            model_name='carpet',
            name='weight',
        ),
        migrations.AddField(
            model_name='carpet',
            name='lanset',
            field=models.CharField(blank=True, max_length=60, verbose_name='Лансет'),
        ),
        migrations.AddField(
            model_name='carpet',
            name='loom_width',
            field=models.CharField(blank=True, max_length=50, verbose_name='Ширина станка'),
        ),
        migrations.AddField(
            model_name='carpet',
            name='machine_number',
            field=models.CharField(blank=True, max_length=50, verbose_name='Номер станка'),
        ),
        migrations.AddField(
            model_name='carpet',
            name='product_name',
            field=models.CharField(blank=True, max_length=120, verbose_name='Наименование'),
        ),
        migrations.AddField(
            model_name='carpet',
            name='quality',
            field=models.CharField(blank=True, max_length=60, verbose_name='Качество'),
        ),
        migrations.AddField(
            model_name='carpet',
            name='thread_type',
            field=models.CharField(blank=True, max_length=120, verbose_name='Вид нитей'),
        ),
        migrations.AddField(
            model_name='carpet',
            name='weight_gross',
            field=models.CharField(blank=True, max_length=30, verbose_name='Брутто кг/м²'),
        ),
        migrations.AddField(
            model_name='carpet',
            name='weight_net',
            field=models.CharField(blank=True, max_length=30, verbose_name='Нетто кг/м²'),
        ),
        migrations.AddField(
            model_name='carpet',
            name='yarn',
            field=models.CharField(blank=True, max_length=120, verbose_name='Пряжа'),
        ),
    ]
