# Generated by Django 5.2.1 on 2025-07-30 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_remove_carpet_thread_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carpet',
            name='thread_material_left',
        ),
        migrations.RemoveField(
            model_name='carpet',
            name='thread_material_right',
        ),
        migrations.RemoveField(
            model_name='carpet',
            name='thread_note',
        ),
        migrations.RemoveField(
            model_name='carpet',
            name='thread_percent_left',
        ),
        migrations.RemoveField(
            model_name='carpet',
            name='thread_percent_right',
        ),
        migrations.AddField(
            model_name='carpet',
            name='thread_type',
            field=models.CharField(blank=True, max_length=120, verbose_name='Вид нитей'),
        ),
    ]
