# Generated by Django 5.2.1 on 2025-07-30 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_remove_carpet_thread_material_left_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carpet',
            name='thread_type',
        ),
        migrations.AddField(
            model_name='carpet',
            name='thread_material_left',
            field=models.CharField(blank=True, max_length=50, verbose_name='Левый материал'),
        ),
        migrations.AddField(
            model_name='carpet',
            name='thread_note',
            field=models.CharField(blank=True, max_length=10, verbose_name='Примечание'),
        ),
        migrations.AddField(
            model_name='carpet',
            name='thread_percent_left',
            field=models.CharField(blank=True, max_length=4, verbose_name='Левый %'),
        ),
        migrations.AddField(
            model_name='carpet',
            name='thread_percent_right',
            field=models.CharField(blank=True, max_length=4, verbose_name='Правый %'),
        ),
    ]
