# Generated by Django 5.2.1 on 2025-07-31 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_remove_carpet_thread_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carpet',
            old_name='weight_net',
            new_name='weight',
        ),
        migrations.RemoveField(
            model_name='carpet',
            name='lanset',
        ),
        migrations.RemoveField(
            model_name='carpet',
            name='weight_gross',
        ),
        migrations.RemoveField(
            model_name='carpet',
            name='yarn',
        ),
    ]
