# Generated by Django 5.2.1 on 2025-07-31 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_rename_weight_net_carpet_weight_remove_carpet_lanset_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carpet',
            name='machine_number',
        ),
        migrations.RemoveField(
            model_name='carpet',
            name='product_name',
        ),
    ]
