# Generated by Django 5.2.1 on 2025-07-31 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_remove_carpet_machine_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='main_colors',
            field=models.CharField(blank=True, max_length=255, verbose_name='Основные цвета (через запятую)'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
