# Generated by Django 5.2.1 on 2025-08-06 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_collection_main_colors_alter_collection_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carpet',
            name='image',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Изображение (URL)'),
        ),
    ]
