# Generated by Django 5.2.3 on 2025-06-13 03:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0005_carpet_backing_carpet_density_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('arrival_date', models.DateField(verbose_name='Дата поступления')),
                ('status', models.CharField(choices=[('created', 'Создана'), ('in_transit', 'В пути'), ('delivered', 'Доставлено')], default='created', max_length=50, verbose_name='Статус')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
            ],
        ),
        migrations.CreateModel(
            name='BatchItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='Количество ковров')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='logistics.batch')),
                ('carpet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.carpet')),
            ],
        ),
    ]
