# Generated by Django 5.2.3 on 2025-06-17 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='destination',
            field=models.CharField(blank=True, max_length=120, verbose_name='Пункт назначения (куда отправляется)'),
        ),
        migrations.AddField(
            model_name='batch',
            name='storage_location',
            field=models.CharField(blank=True, max_length=100, verbose_name='Место хранения (склад)'),
        ),
    ]
